import './globals.css'
import type { Metadata } from 'next'
import { Inter,Poppins } from 'next/font/google'
import Header from './Components/Header'
import Footer from './Components/Footer'

// const inter = Inter({ subsets: ['latin'] })

const poppins =Poppins({
    subsets:['latin'],
    display:'swap',
    weight: ["100","200","300","400","500","600","700","800","900"],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header/>
        {children}
        <Footer/>

        {/* <script src="../path/to/flowbite/dist/flowbite.min.js"></script> */}
        </body>
    </html>
  )
}
